### ISSUE TITLE
compile issue

### ISSUE THREAD

**Issue by mattstep** [GoogleCloudPlatform/appengine-guestbook-java#12]
https://github.com/GoogleCloudPlatform/appengine-guestbook-java/commit/e9c0fb21da743b56b66d829061cadb27342c97cc#diff-600376dffeb79835ede4a0b285078036L74 incorrectly removed the compiler plugin definition that set the right source version

**Comment by tmatsuo** [comment]
I think it's obsolete, closing. Feel free to open it if you feel differently.
