### ISSUE TITLE
Using Angularjs.

### ISSUE THREAD

**Issue by vivekimsit** [GoogleCloudPlatform/appengine-guestbook-java#16]
Is there any tutorial/way to build the same app using Angularjs?

**Comment by ludoch** [comment]
https://github.com/googlearchive/appengine-angular-guestbook-java

**Comment by vivekimsit** [comment]
Thanks,

But the given link seems too old, also I think its some other framework. I was thinking if some simple solution exists for servlets on AppEngine.

**Comment by ludoch** [comment]
The point of this sample it to show the same app code that worked in 2010 on java6 App Engine Beta still works with App Engine Java 8, Java 11 and Java 17... PAAS forever.
